### ISSUE TITLE
Broken after recent update with: lsp-java-errors-incomplete-classpath-severity

### ISSUE THREAD

**Issue by chookity-pokk** [emacs-lsp/lsp-java#442]
**Describe the bug**
I just did an update and now lsp-java doesn't work. Opening a Java file and using lsp-mode just gives the below error.
`Symbol’s value as variable is void: lsp-java-errors-incomplete-classpath-severity`

**To Reproduce**
Update to the most recent release (`lsp-java-20230615.614`) and try to use lsp-mode on a Java file.

**Logs**
Below are the debug logs. 

```
Debugger entered--Lisp error: (void-variable lsp-java-errors-incomplete-classpath-severity)
  byte-code("\306\307\310\311\312DD\313\314\315\316\317&\7\210\306\320\310\311\321DD\322\314\315\316\317&\7\210\306\323\310\311\324DD\325\316\317\326\327&\7\210\306\330\310\311\331..." [lsp-java-errors-incomplete-classpath-severity lsp-java-dependency-package-representation lsp-java-configuration-check-project-settings-exclusions lsp-java-configuration-update-build-configuration lsp-java-trace-server lsp-java-import-gradle-enabled custom-declare-variable lsp-java-workspace-dir funcall function #f(compiled-function () #<bytecode -0x15a9c83b9c820544>) "LSP java workspace directory." :risky t :type directory lsp-java-workspace-cache-dir #f(compiled-function () #<bytecode 0x199de1997623c>) "LSP java workspace cache directory." lsp-java-themes-directory #f(compiled-function () #<bytecode -0xbec6b92eeb638a3>) "Directory containing themes." :group lsp-java lsp-java-theme #f(compiled-function () #<bytecode 0x1980e443fd9d4>) "Theme to use." string lsp-java-pop-buffer-function #f(compiled-function () #<bytecode 0x1980145c8be54>) "The function which will be used for showing the he..." lsp-java-vmargs #f(compiled-function () #<bytecode -0x1407c85e2847739c>) "Specifies extra VM arguments used to launch the Ja..." (repeat string) lsp-java-9-args #f(compiled-function () #<bytecode 0x105f88891bcddea1>) "Specifies arguments specific to java 9 and later." (repeat string) lsp-defcustom "warning" "Specifies the severity of the message when the cla..." (choice (const "ignore") (const "info") (const "warning") (const "error")) :lsp-path "java.errors.incompleteClasspath.severity" "flat" (choice (const "flat") (const "hierarchical")) "java.dependency.packagePresentation" "Checks if the extension-generated project settings..." boolean ...] 8)
  require(lsp-java nil t)
  (not (require 'lsp-java nil t))
  (if (not (require 'lsp-java nil t)) (display-warning 'use-package (format "Cannot load %s" 'lsp-java) :error) (condition-case err (progn (add-hook 'java-mode-hook 'lsp) t) ((debug error) (funcall use-package--warning14 :config err))))
  (condition-case err (if (not (require 'lsp-java nil t)) (display-warning 'use-package (format "Cannot load %s" 'lsp-java) :error) (condition-case err (progn (add-hook 'java-mode-hook 'lsp) t) ((debug error) (funcall use-package--warning14 :config err)))) ((debug error) (funcall use-package--warning14 :catch err)))
  load-with-code-conversion("/home/hank/.emacs.d/init.el" "/home/hank/.emacs.d/init.el" nil nil)
  load-file("/home/hank/.emacs.d/init.el")
  org-babel-load-file("/home/hank/.emacs.d/init.org")
  load-with-code-conversion("/home/hank/.emacs" "/home/hank/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x175b640586801f7b>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()
```

I am using lsp-java on Emacs 29.0.9 on Arch Linux. I'm not sure what version I was using before the update (it's been a while since I updated packages), but it worked for a few months then.

**Comment by vanniuner** [comment]
lsp require jdk17 now，check it frist

**Comment by vanniuner** [comment]
You can try here are some setting needful.
```
(setq lsp-java-format-settings-url   (expand-file-name (concat doom-user-dir "neoemacs/Intellij_Spring_Boot_Java_Conventions.xml"))
      lsp-java-java-path             (concat "/Users/van/soft/jdk/jdk-17.0.6.jdk/Contents/Home/bin/java")
      lsp-maven-path                 "~/.m2/settings.xml"
      lsp-java-configuration-maven-user-settings (expand-file-name lsp-maven-path )
      lombok-jar-path                ( expand-file-name (concat doom-user-dir "neoemacs/lombok.jar")))
```

**Comment by yyoncho** [comment]
@chookity-pokk first, try clean reinstall. (Deleting elpa dir, restarting emacs, installing the packages)

**Comment by chookity-pokk** [comment]
@yyoncho I tried that twice yesterday without any luck (though I forgot to put that in my report, sorry), but doing it again just now and it seems to be working. Not sure what the difference is, but this is fixed now.

**Comment by chookity-pokk** [comment]
@vanniuner Thanks for the settings!

**Comment by omarbassam88** [comment]
I have the same issue I tried installing jdk 17 and reinstalling the package in emacs but I still get the same error. I did try the settings mentioned above. Still not working for me
